# The container is used to test the LLM model, reads the pdf, ask the questions, and save the answers.
FROM python:3.9.18

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . .

# Install requirements
RUN pip install numpy scipy
RUN pip install torch==2.1.0
RUN pip install -r requirements.txt

# Run a command
RUN python main.py

CMD ["/bin/sh", "-c", "bash"]
