# The container is used to test the LLM model, reads the pdf, ask the questions, and save the answers.
# Build: docker build -t llm_test .
# Run: docker run -it --rm --name llm_test llm_test
# Run: docker run -it --rm --name llm_test -v ./data llm_test

FROM python:3.9.18

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . .

# Install requirements
RUN pip install -r requirements.txt

# Run a command
CMD ["python", "main.py"]